
google_analytics: UA-37021710-1

disqus: brookeandsons
disqus_generate_id: true

profiles:
  development:
  production:
    base_url: http://brookesonsweb.com
    deploy:
      host: github_pages
      branch: gh-pages
